rg_name = "RG_VDI"
deploy_location = "west europe"
hp_name = "vdi_hp"
hp_fr_name = "vdi_friendlyhp"
hp_descript = "Some hp"

appgr_name = "vdiappgr"
appgr_type = "Desktop"
appgr_fr_name = "appgr_friendly_name"
appgr_descript = "appgr description"
appgr_disp_name = "Default desktop"
workspace_id = "/subscriptions/2020d672-be3c-4669-a97d-edc7704c5c17/resourceGroups/RG_VDI/providers/Microsoft.DesktopVirtualization/workspaces/vdi_workspace"